paths:
  public: "public"
groups:
  scripts:
    paths:
      - app/scripts
    concat:
      "/form-tip.js": "{app,vendor}/**/*.{js,coffee}"
      "../form-tip.js": "{app,vendor}/**/*.{js,coffee}"
    order:
      - vendor/jquery.js
      - vendor/handlebars.js
      - vendor/templates.js
      - app/scripts/helper/validate.coffee
      - app/scripts/helper/pattern.coffee
      - ...
      - app/scripts/app.coffee
  styles:
    paths:
      - app/styles
    concat:
      "/form-tip.css": "app/styles/**/[a-z]*.{css,scss,sass}"
      "../form-tip.css": "app/styles/**/[a-z]*.{css,scss,sass}"
  images:
    paths:
      - app/images
    sprite:
      "../app/styles/icons.scss": "app/images/**/*.png"
  views:
    paths:
      - app/views
    copy:
      "/": "app/views/**/*.html"
  templates:
    paths:
      - app/scripts
    precompile:
      "../vendor/templates.js": "app/**/*.hbs"
modules:
  wrapper: cmd
  ignored: vendor/**/*
  definition: /form-tip.js
sprites:
  path: ../
  path: images/
  selector: .icon-
revision:
  files:
    - index.html
notification: true
bundles:
  handlebars.js:
    version: 1.3.0
    url: http://builds.handlebarsjs.com.s3.amazonaws.com/handlebars.runtime-v1.3.0.js
  jquery.js:
    version: 1.10.2
    url: http://code.jquery.com/jquery-1.10.2.js
